### ISSUE TITLE
Unrelated

### ISSUE THREAD

**Issue by Michael21107** [nonameset/TrafficLightController#1]
hey, sorry for contacting you here; I didn't find any other way, is there one perhaps?

**Comment by nonameset** [comment]
Hey, yes. You can contact me on Discord (.nonameset) :)

**Comment by Michael21107** [comment]
thank you very much ❤️

**Comment by Michael21107** [comment]
@nonameset it says you are not accepting friend requests tho, and I don't think there's a way to DM someone without at least sending him a request first, my username is michael21107 and I'd really appreciate you adding me
